#!/usr/bin/env php
<?php

declare(strict_types=1);

ini_set('display_errors', 1);

// Change this relative path to application and internal directory parent
define('PATH_FROM_INDEX_TO_APPLICATION', __DIR__ . DIRECTORY_SEPARATOR . '.' . DIRECTORY_SEPARATOR);

include './Common/AutoLoader.php';

use Common\Autoloader;
use Scripts\Commands\Help\Help;
use Scripts\Commands\ResolveCommand;
use Scripts\Commands\Start\Start;
use Scripts\Console\ConsoleSingleton;

AutoLoader::Register();

ConsoleSingleton::RegisterConsole($argv, STDOUT, STDERR);

$avaliableCommands = [
	Start::class,
	Help::class
];

$resolver = new ResolveCommand($avaliableCommands);

$resolver->resolve();
